server:
  port: 8081

spring:
  application:
    name: TraditionalWeb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.5.137:3306/security?serverTimezone=UTC

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl